-- Research-only V2 artifact. This schema is not used by V1 serving.
CREATE TABLE IF NOT EXISTS v2_flight_records (
    flight_date DATE NOT NULL,
    reporting_carrier VARCHAR NOT NULL,
    flight_number VARCHAR,
    tail_number VARCHAR,
    origin CHAR(3) NOT NULL,
    destination CHAR(3) NOT NULL,
    origin_airport_id INTEGER NOT NULL,
    destination_airport_id INTEGER NOT NULL,
    crs_departure_minutes SMALLINT NOT NULL,
    departure_minutes SMALLINT,
    crs_arrival_minutes SMALLINT NOT NULL,
    arrival_minutes SMALLINT,
    departure_delay_minutes DOUBLE,
    arrival_delay_minutes DOUBLE,
    cancelled BOOLEAN NOT NULL,
    diverted BOOLEAN NOT NULL,
    cancellation_code VARCHAR,
    taxi_out_minutes DOUBLE,
    wheels_off_minutes SMALLINT,
    wheels_on_minutes SMALLINT,
    taxi_in_minutes DOUBLE,
    crs_elapsed_minutes DOUBLE,
    actual_elapsed_minutes DOUBLE,
    air_time_minutes DOUBLE,
    distance_miles DOUBLE,
    carrier_delay_minutes DOUBLE,
    weather_delay_minutes DOUBLE,
    nas_delay_minutes DOUBLE,
    security_delay_minutes DOUBLE,
    late_aircraft_delay_minutes DOUBLE,
    first_departure_minutes SMALLINT,
    total_additional_ground_minutes DOUBLE,
    longest_additional_ground_minutes DOUBLE,
    diversion_airport_landings SMALLINT,
    diversion_reached_destination BOOLEAN,
    diversion_actual_elapsed_minutes DOUBLE,
    diversion_arrival_delay_minutes DOUBLE,
    diversion_distance_miles DOUBLE,
    diversion_details JSON,
    source_file VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS v2_data_quality_monthly (
    source_file VARCHAR PRIMARY KEY,
    source_rows BIGINT NOT NULL,
    retained_rows BIGINT NOT NULL,
    invalid_core_rows BIGINT NOT NULL,
    missing_flight_number_rows BIGINT NOT NULL,
    cancelled_rows BIGINT NOT NULL,
    diverted_rows BIGINT NOT NULL
);
